title: Philadelphia Neighborhood Clusters
logo: /assets/img/logo.png
description: Created by Jack Rummler
show_downloads: false
repository: jtrummler/PhillyClusters
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
