title: Cluster215
description: What defines each neighborhood in Philadelphia? A cluster analysis of Philadelphia, PA
show_downloads: false
repository: jtrummler/PhillyClusters
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
